import { StatsCards } from "./widgets/stats-cards";
import { UpcomingSessions } from "./widgets/upcoming-sessions";
import { TeamStatus } from "./widgets/team-status";
import { RevenueWidget } from "./widgets/revenue-widget";
import { CalendarWidget } from "./widgets/calendar-widget";
import { NotesWidget } from "./widgets/notes-widget";
import { RevenueBarChartWidget } from "./widgets/revenue-bar-chart";
import { OccupancyPieChartWidget } from "./widgets/occupancy-pie-chart";
import { QuarterlyStatsWidget } from "./widgets/quarterly-stats";
import { RevenueTableWidget } from "./widgets/revenue-table";
import { FiscalWidget } from "./widgets/FiscalWidget";
import { ProjectedEarningsWidget } from "./widgets/ProjectedEarningsWidget";
import { RecentBookingsWidget } from "./widgets/recent-bookings";
import { PendingPaymentsWidget } from "./widgets/pending-payments";
import { StaffClockWidget } from "./widgets/staff-clock";
import { PendingVacationsWidget } from "./widgets/pending-vacations";
import { ActiveCouponsWidget } from "./widgets/active-coupons";
import { RecentPaymentsWidget } from "./widgets/recent-payments";
import { RoomsStatusWidget } from "./widgets/rooms-status";
import { QuickLinksWidget } from "./widgets/quick-links";
import { DigitalClockWidget } from "./widgets/digital-clock";
import { UnreadNotificationsWidget } from "./widgets/unread-notifications";
import { WidgetDefinition } from "./types";

export const WIDGET_REGISTRY: Record<string, WidgetDefinition> = {
  stats: {
    type: "stats",
    title: "Estadísticas Generales",
    description: "Resumen de reservas, ingresos y ocupación",
    component: StatsCards,
    defaultColSpan: 48,
    defaultRowSpan: 14,
    configurableOptions: [
      "showTrends",
      "columns",
      "refreshInterval",
      "visibleStats",
    ],
    defaultConfig: {
      showTrends: true,
      columns: 4,
      refreshInterval: 60,
      visibleStats: ["revenue", "bookings", "customers", "rooms"],
    },
  },
  upcoming: {
    type: "upcoming",
    title: "Próximas Sesiones",
    description: "Lista de las próximas sesiones programadas",
    component: UpcomingSessions,
    defaultColSpan: 24,
    defaultRowSpan: 35,
    minColSpan: 12,
    minRowSpan: 25,
    configurableOptions: ["limit", "showPastSessions", "refreshInterval"],
    defaultConfig: { limit: 5, showPastSessions: false, refreshInterval: 30 },
  },
  team: {
    type: "team",
    title: "Estado del Equipo",
    description: "Disponibilidad y estado actual de los empleados",
    component: TeamStatus,
    defaultColSpan: 16,
    defaultRowSpan: 25,
    minColSpan: 12,
    minRowSpan: 20,
    configurableOptions: ["refreshInterval"],
    defaultConfig: { refreshInterval: 60 },
  },
  revenue: {
    type: "revenue",
    title: "Ingresos (Simple)",
    description: "Resumen de ingresos mensuales",
    component: RevenueWidget,
    defaultColSpan: 24,
    defaultRowSpan: 22,
    minColSpan: 16,
    minRowSpan: 18,
    configurableOptions: ["defaultPeriod", "targetMonthly"],
    defaultConfig: { title: "Ingresos (Simple)", defaultPeriod: "month", targetMonthly: 10000 },
  },
  calendar: {
    type: "calendar",
    title: "Calendario",
    description: "Vista de calendario mensual/semanal",
    component: CalendarWidget,
    defaultColSpan: 16,
    defaultRowSpan: 30,
    minColSpan: 12,
    minRowSpan: 20,
    configurableOptions: ["defaultView", "showWeekends"],
    defaultConfig: { defaultView: "month", showWeekends: true },
  },
  notes: {
    type: "notes",
    title: "Notas Rápidas",
    description: "Bloc de notas simple",
    component: NotesWidget,
    defaultColSpan: 12,
    defaultRowSpan: 18,
    minColSpan: 8,
    minRowSpan: 12,
    configurableOptions: ["maxNotes"],
    defaultConfig: { maxNotes: 10 },
  },
  "revenue-chart": {
    type: "revenue-chart",
    title: "Gráfico Ingresos vs Gastos",
    description: "Comparativa mensual de ingresos y gastos",
    component: RevenueBarChartWidget,
    defaultColSpan: 32,
    defaultRowSpan: 32,
    minColSpan: 20,
    minRowSpan: 24,
    configurableOptions: ["chartType", "showLegend", "dateRange"],
    defaultConfig: { chartType: "bar", showLegend: true, dateRange: "month" },
  },
  "occupancy-chart": {
    type: "occupancy-chart",
    title: "Ocupación por Sala",
    description: "Distribución de reservas por sala",
    component: OccupancyPieChartWidget,
    defaultColSpan: 16,
    defaultRowSpan: 28,
    minColSpan: 12,
    minRowSpan: 20,
    configurableOptions: ["showLegend", "dateRange"],
    defaultConfig: { showLegend: true, dateRange: "month" },
  },
  "quarterly-stats": {
    type: "quarterly-stats",
    title: "Resumen Trimestral",
    description: "KPIs principales del trimestre actual",
    component: QuarterlyStatsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 22,
    minColSpan: 16,
    minRowSpan: 18,
    configurableOptions: ["refreshInterval"],
    defaultConfig: { refreshInterval: 300 },
  },
  "revenue-table": {
    type: "revenue-table",
    title: "Registro de Transacciones",
    description: "Tabla detallada de ingresos con filtros",
    component: RevenueTableWidget,
    defaultColSpan: 48,
    defaultRowSpan: 45,
    minColSpan: 24,
    minRowSpan: 35,
    configurableOptions: ["pageSize", "sortBy", "dateRange"],
    defaultConfig: { pageSize: 10, sortBy: "date", dateRange: "month" },
  },
  fiscal: {
    type: "fiscal",
    title: "Ingresos (Facturación)",
    description: "Resumen de facturación mensual",
    component: RevenueWidget,
    defaultColSpan: 24,
    defaultRowSpan: 22,
    minColSpan: 16,
    minRowSpan: 18,
    configurableOptions: ["defaultPeriod", "targetMonthly"],
    defaultConfig: { title: "Facturación", defaultPeriod: "month", targetMonthly: 15000 },
  },
  projected: {
    type: "projected",
    title: "Proyección Mensual",
    description: "Ganado vs Pendiente mes actual",
    component: ProjectedEarningsWidget,
    defaultColSpan: 12,
    defaultRowSpan: 22,
    minColSpan: 12,
    minRowSpan: 18,
    configurableOptions: ["defaultPeriod", "targetMonthly"],
    defaultConfig: { defaultPeriod: "month", targetMonthly: 20000 },
  },
  "recent-bookings": {
    type: "recent-bookings",
    title: "Últimas Reservas",
    description: "Listado de las reservas recibidas más recientemente",
    component: RecentBookingsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 35,
    minColSpan: 16,
    minRowSpan: 25,
    configurableOptions: ["limit"],
    defaultConfig: { limit: 5 },
  },
  "pending-payments": {
    type: "pending-payments",
    title: "Pagos Pendientes",
    description: "Reservas activas con saldos deudores",
    component: PendingPaymentsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 28,
    minColSpan: 16,
    minRowSpan: 20,
    configurableOptions: ["limit", "sortBy"],
    defaultConfig: { limit: 10, sortBy: "amount" },
  },
  "staff-clock": {
    type: "staff-clock",
    title: "Fichajes (Asistencia)",
    description: "Últimos registros de entrada y salida del personal",
    component: StaffClockWidget,
    defaultColSpan: 16,
    defaultRowSpan: 30,
    minColSpan: 12,
    minRowSpan: 20,
    configurableOptions: ["limit", "refreshInterval"],
    defaultConfig: { limit: 8, refreshInterval: 60 },
  },
  "pending-vacations": {
    type: "pending-vacations",
    title: "Vacaciones Pendientes",
    description: "Solicitudes de tiempo libre pendientes de revisión",
    component: PendingVacationsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 30,
    minColSpan: 16,
    minRowSpan: 20,
    configurableOptions: ["limit", "sortBy"],
    defaultConfig: { limit: 5, sortBy: "date" },
  },
  "active-coupons": {
    type: "active-coupons",
    title: "Cupones Activos",
    description: "Monitor de campañas vigentes",
    component: ActiveCouponsWidget,
    defaultColSpan: 16,
    defaultRowSpan: 22,
    minColSpan: 12,
    minRowSpan: 18,
    configurableOptions: ["limit", "sortBy"],
    defaultConfig: { limit: 5, sortBy: "name" },
  },
  "recent-payments": {
    type: "recent-payments",
    title: "Pagos Recientes",
    description: "Últimas transacciones económicas exitosas",
    component: RecentPaymentsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 30,
    minColSpan: 16,
    minRowSpan: 25,
    configurableOptions: ["limit", "dateRange"],
    defaultConfig: { limit: 10, dateRange: "month" },
  },
  "rooms-status": {
    type: "rooms-status",
    title: "Estado de Salas",
    description: "Resumen de capacidades y tarifas activas",
    component: RoomsStatusWidget,
    defaultColSpan: 24,
    defaultRowSpan: 28,
    minColSpan: 16,
    minRowSpan: 22,
    configurableOptions: ["refreshInterval"],
    defaultConfig: { refreshInterval: 60 },
  },
  "quick-links": {
    type: "quick-links",
    title: "Accesos Rápidos",
    description: "Botones para ir directamente a la vista deseada",
    component: QuickLinksWidget,
    defaultColSpan: 16,
    defaultRowSpan: 20,
    minColSpan: 12,
    minRowSpan: 15,
    configurableOptions: ["columns"],
    defaultConfig: { columns: 4 },
  },
  "digital-clock": {
    type: "digital-clock",
    title: "Reloj Digital",
    description: "Hora local para modo de recepción",
    component: DigitalClockWidget,
    defaultColSpan: 16,
    defaultRowSpan: 18,
    minColSpan: 12,
    minRowSpan: 15,
    configurableOptions: ["title"],
    defaultConfig: { title: "Reloj Digital" },
  },
  "unread-notifications": {
    type: "notifications",
    title: "Notificaciones del Sistema",
    description: "Mensajes y alertas sin leer",
    component: UnreadNotificationsWidget,
    defaultColSpan: 24,
    defaultRowSpan: 25,
    minColSpan: 16,
    minRowSpan: 20,
    configurableOptions: ["limit", "refreshInterval"],
    defaultConfig: { limit: 5, refreshInterval: 60 },
  },
};
